spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

logging:
  config: jdbc/logback.xml